#!/bin/bash
#
# lib/security.sh - Security hardening functions
#

SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/utils.sh"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/wizard.sh"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/safety.sh"

# Harden SSH configuration
# Creates a hardened sshd_config with security best practices
harden_ssh() {
    log_info "Configuring SSH hardening..."

    # Get configuration values
    local ssh_port username
    ssh_port=$(get_config "ssh_port")
    username=$(get_config "username")

    # Validate configuration
    if [[ -z "$ssh_port" ]]; then
        log_error "SSH port not configured"
        return 1
    fi

    if [[ -z "$username" ]]; then
        log_error "Username not configured"
        return 1
    fi

    # In dry-run mode, just simulate SSH hardening
    if [[ "$DRY_RUN" == "true" ]]; then
        echo -e "${YELLOW}[DRY-RUN]${NC} Would configure SSH hardening"
        echo -e "${YELLOW}[DRY-RUN]${NC} Would set SSH port to $ssh_port"
        echo -e "${YELLOW}[DRY-RUN]${NC} Would disable root login"
        echo -e "${YELLOW}[DRY-RUN]${NC} Would disable password authentication"
        echo -e "${YELLOW}[DRY-RUN]${NC} Would restart SSH service"
        return 0
    fi

    local sshd_config="/etc/ssh/sshd_config"
    
    # Backup original configuration
    backup_file "$sshd_config"
    
    # Create hardened configuration
    log_verbose "Creating hardened sshd_config..."
    
    cat > "$sshd_config" << EOF
# Hardened SSH configuration generated by uservin
# Original config backed up

# Network settings
Port $ssh_port
AddressFamily any
ListenAddress 0.0.0.0
ListenAddress ::

# Protocol settings
Protocol 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Ciphers and algorithms
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256

# Authentication settings
PasswordAuthentication no
PermitEmptyPasswords no
PubkeyAuthentication yes
PermitRootLogin no
AllowUsers $username
AuthenticationMethods publickey

# Session settings
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
PermitTunnel no
GatewayPorts no
LoginGraceTime 60
MaxAuthTries 3
MaxSessions 2
ClientAliveInterval 300
ClientAliveCountMax 2

# Logging
SyslogFacility AUTH
LogLevel INFO

# Banner
UsePAM yes
PrintMotd no
PrintLastLog yes

# Environment
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
EOF
    
    log_verbose "SSH configuration written successfully"
    
    # Test configuration before applying
    log_verbose "Testing SSH configuration..."
    if ! sshd -t; then
        log_error "SSH configuration test failed - configuration may be invalid"
        return 1
    fi
    
    log_success "SSH configuration test passed"
    
    # Restart SSH service
    log_verbose "Restarting SSH service..."
    if cmd_exists systemctl; then
        if systemctl restart sshd 2>/dev/null || systemctl restart ssh; then
            log_success "SSH service restarted successfully"
        else
            log_error "Failed to restart SSH service"
            return 1
        fi
    else
        log_warn "systemctl not available - cannot restart SSH service"
        return 1
    fi
    
    # Verify SSH is listening on the configured port
    sleep 1
    if ss -tlnp | grep -q ":$ssh_port "; then
        log_success "SSH is listening on port $ssh_port"
    else
        log_warn "SSH may not be listening on port $ssh_port"
    fi
    
    log_success "SSH hardening completed"
    return 0
}

# Configure UFW firewall
# Sets up UFW with secure defaults and SSH access
configure_ufw() {
    log_info "Configuring UFW firewall..."
    
    # Get SSH port
    local ssh_port
    ssh_port=$(get_config "ssh_port")
    
    if [[ -z "$ssh_port" ]]; then
        log_error "SSH port not configured"
        return 1
    fi
    
    # In dry-run mode, just simulate UFW configuration
    if [[ "$DRY_RUN" == "true" ]]; then
        echo -e "${YELLOW}[DRY-RUN]${NC} Would configure UFW firewall"
        echo -e "${YELLOW}[DRY-RUN]${NC} Would allow SSH port $ssh_port"
        echo -e "${YELLOW}[DRY-RUN]${NC} Would enable UFW with default deny incoming"
        return 0
    fi
    
    # Check if UFW is installed
    if ! cmd_exists ufw; then
        log_error "UFW is not installed"
        return 1
    fi
    
    # Reset UFW to defaults
    log_verbose "Resetting UFW to defaults..."
    echo "y" | ufw reset &>/dev/null
    
    # Set default policies
    log_verbose "Setting default policies..."
    ufw default deny incoming &>/dev/null
    ufw default allow outgoing &>/dev/null
    
    # Allow SSH port
    log_verbose "Allowing SSH port $ssh_port..."
    ufw allow "$ssh_port/tcp" comment "SSH access" &>/dev/null
    
    # Rate limit SSH to prevent brute force
    log_verbose "Setting up SSH rate limiting..."
    ufw limit "$ssh_port/tcp" comment "SSH rate limit" &>/dev/null
    
    # Enable logging
    log_verbose "Enabling UFW logging..."
    ufw logging on &>/dev/null
    
    # Enable UFW
    log_verbose "Enabling UFW..."
    echo "y" | ufw enable &>/dev/null
    
    log_success "UFW firewall configured successfully"
    
    # Show status
    log_info "UFW Status:"
    ufw status verbose
    
    return 0
}

# Configure Fail2ban
# Sets up intrusion prevention for SSH
configure_fail2ban() {
    log_info "Configuring Fail2ban..."

    # Get SSH port
    local ssh_port
    ssh_port=$(get_config "ssh_port")

    if [[ -z "$ssh_port" ]]; then
        log_error "SSH port not configured"
        return 1
    fi

    # In dry-run mode, just simulate fail2ban configuration
    if [[ "$DRY_RUN" == "true" ]]; then
        echo -e "${YELLOW}[DRY-RUN]${NC} Would configure Fail2ban"
        echo -e "${YELLOW}[DRY-RUN]${NC} Would set SSH port to $ssh_port"
        echo -e "${YELLOW}[DRY-RUN]${NC} Would create /etc/fail2ban/jail.local"
        return 0
    fi

    # Check if fail2ban is installed
    if ! cmd_exists fail2ban-server; then
        log_error "Fail2ban is not installed"
        return 1
    fi

    local jail_local="/etc/fail2ban/jail.local"
    
    # Backup existing jail.local if it exists
    if [[ -f "$jail_local" ]]; then
        backup_file "$jail_local"
    fi
    
    # Create jail.local configuration
    log_verbose "Creating Fail2ban configuration..."
    
    cat > "$jail_local" << EOF
# Fail2ban configuration generated by uservin
# See man jail.conf for more information

[DEFAULT]
# Ban time (1 hour)
bantime = 1h

# Time window for max retries (10 minutes)
findtime = 10m

# Maximum failed attempts before ban
maxretry = 5

# Use systemd backend for journald
backend = systemd

# Email notifications (optional - requires configuration)
destemail = root@localhost
sendername = Fail2ban

# Actions
action = %(action_)s

[sshd]
enabled = true
port = $ssh_port
filter = sshd
mode = aggressive
logpath = %(sshd_log)s
backend = systemd

# Stricter settings for SSH
maxretry = 3
bantime = 1h
findtime = 10m

# Ban persistent attackers longer
bantime.increment = true
bantime.factor = 2
bantime.maxtime = 48h
EOF
    
    log_verbose "Fail2ban configuration written successfully"
    
    # Restart fail2ban service
    log_verbose "Restarting Fail2ban service..."
    if cmd_exists systemctl; then
        if systemctl restart fail2ban; then
            log_success "Fail2ban service restarted successfully"
        else
            log_error "Failed to restart Fail2ban service"
            return 1
        fi
        
        # Enable on boot
        if systemctl enable fail2ban &>/dev/null; then
            log_success "Fail2ban enabled on boot"
        else
            log_warn "Failed to enable Fail2ban on boot"
        fi
    else
        log_warn "systemctl not available - cannot manage Fail2ban service"
        return 1
    fi
    
    # Show status
    log_info "Fail2ban Status:"
    if cmd_exists fail2ban-client; then
        fail2ban-client status sshd 2>/dev/null || log_warn "Could not get Fail2ban status"
    fi
    
    log_success "Fail2ban configuration completed"
    return 0
}

# Configure automatic updates
# Sets up unattended-upgrades for security updates only
configure_auto_updates() {
    log_info "Configuring automatic security updates..."
    
    local unattended_conf="/etc/apt/apt.conf.d/50unattended-upgrades"
    local auto_upgrades_conf="/etc/apt/apt.conf.d/20auto-upgrades"
    
    # Check if file exists
    if [[ ! -f "$unattended_conf" ]]; then
        log_warn "Unattended-upgrades configuration not found at $unattended_conf"
        log_info "Attempting to create basic configuration..."
        
        # Create directory if needed
        mkdir -p "$(dirname "$unattended_conf")"
    else
        # Backup existing configuration
        backup_file "$unattended_conf"
    fi
    
    # Create unattended-upgrades configuration
    log_verbose "Creating unattended-upgrades configuration..."
    
    cat > "$unattended_conf" << 'EOF'
// Unattended upgrades configuration generated by uservin
// See man unattended-upgrades for more information

// Automatically upgrade packages from these origins
Unattended-Upgrade::Allowed-Origins {
    "\${distro_id}:\${distro_codename}-security";
    "\${distro_id}ESMApps:\${distro_codename}-apps-security";
    "\${distro_id}ESM:\${distro_codename}-infra-security";
};

// Remove unused automatically installed kernel-related packages
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

// Remove unused dependencies
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// Automatically reboot if required (disabled by default - user should configure)
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Automatic-Reboot-Time "02:00";

// Automatically fix broken dpkg
Unattended-Upgrade::AutoFixInterruptedDpkg "true";

// Minimal steps to avoid taking up too much resource
Unattended-Upgrade::MinimalSteps "true";

// Send email reports (optional)
// Unattended-Upgrade::Mail "root";
// Unattended-Upgrade::MailReport "on-change";

// Clean up downloaded packages after installation
Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
EOF
    
    log_verbose "Unattended-upgrades configuration written"
    
    # Create auto-upgrades configuration for periodic updates
    log_verbose "Creating auto-upgrades configuration..."
    
    cat > "$auto_upgrades_conf" << 'EOF'
// Auto-upgrades configuration generated by uservin
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
EOF
    
    log_verbose "Auto-upgrades configuration written"
    
    # Restart unattended-upgrades service
    log_verbose "Restarting unattended-upgrades service..."
    if cmd_exists systemctl; then
        if systemctl restart unattended-upgrades 2>/dev/null || true; then
            log_verbose "Unattended-upgrades service restarted"
        fi
        
        # Enable on boot
        if systemctl enable unattended-upgrades 2>/dev/null; then
            log_success "Unattended-upgrades enabled on boot"
        else
            log_warn "Failed to enable unattended-upgrades on boot (package may not be installed)"
        fi
    fi
    
    log_success "Automatic security updates configured"
    return 0
}
